elasticcommonfields: {}
id: Malware Domain List Active IPs Feed Test
version: -1
name: Malware Domain List Active IPs Feed Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6aac6b92-8cfe-4ac2-89bc-beec334da0ba
    type: start
    task:
      elasticcommonfields: {}
      id: 6aac6b92-8cfe-4ac2-89bc-beec334da0ba
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: b2854659-f445-4ca9-8630-95a72705a167
    type: regular
    task:
      elasticcommonfields: {}
      id: b2854659-f445-4ca9-8630-95a72705a167
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 4dc3d264-a143-4d8e-875d-69045ef24df7
    type: regular
    task:
      elasticcommonfields: {}
      id: 4dc3d264-a143-4d8e-875d-69045ef24df7
      version: -1
      name: get-indicators-ip
      description: Gets the feed indicators.
      script: Malware Domain List Active IPs Feed|||malwaredomainlist-get-indicators
      type: regular
      iscommand: true
      brand: Malware Domain List Active IPs Feed
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 211c9331-4531-4738-8961-b8c3d385878c
    type: condition
    task:
      elasticcommonfields: {}
      id: 211c9331-4531-4738-8961-b8c3d385878c
      version: -1
      name: verify get indicators
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Type
            iscontext: true
          right:
            value:
              simple: IP
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 2232e537-326e-4c21-8ce8-648d51595106
    type: title
    task:
      elasticcommonfields: {}
      id: 2232e537-326e-4c21-8ce8-648d51595106
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: AWS Feed Test
fromversion: 5.5.0